name: Build and Deploy PRODUCTION

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-node@v2
        with:
          node-version: 'v21.5.0'
      - name: Clean temp files
        run: rm -rf node_modules
      - name: Install Dependencies
        run: npm install
      - name: Build
        run:  npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/${{vars.DESTINATION_FOLDER }}
          include-hidden-files: true
          overwrite: true
        # env:
          # ACTIONS_STEP_DEBUG: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/${{vars.DESTINATION_FOLDER}}
      - name: Transfer files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.GIT_SSH}} 
          port: ${{ secrets.PORT }}
          source: ${{ vars.DESTINATION_FOLDER }}
          target: ${{ secrets.MACHINE_DEST_FOLDER }}
      - name: Reload project
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.GIT_SSH }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 reload hf --update-env